export const ADD_FILTER = "ADD_FILTER";
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT"
export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_PRODUCTS_CART = "DELETE_PRODUCTS_CART"
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART"
export const ADD_PRODUCTS_CART_HOME = "ADD_PRODUCTS_CART_HOME";
export const NEWPRODUCT_FORM = "NEWPRODUCT_FORM"
export const FILTER_BY_LANDING_PAGE = "FILTER_BY_LANDING_PAGE"
export const ORDER_DETIALS = "ORDER_DETIALS"
export const GET_ONE_USER = "GET_ONE_USER"
export const ERRORS = "ERRORS"
export const GET_COMMENTS_PRODUCT = "GET_COMMENTS_PRODUCT"
export const POST_NEW_COMMENT = "POST_NEW_COMMENT"
export const GET_ALL_USERS = "GET_ALL_USERS"



